//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_PriTaskController : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerPress
        {
            get
            {
                return SteamVR_Actions.priTaskController_TriggerPress;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.priTaskController_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackpadSwipeXY
        {
            get
            {
                return SteamVR_Actions.priTaskController_TrackpadSwipeXY;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackPadXYPosition
        {
            get
            {
                return SteamVR_Actions.priTaskController_TrackPadXYPosition;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackPadSwipeX
        {
            get
            {
                return SteamVR_Actions.priTaskController_TrackPadSwipeX;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackPadNorthClick
        {
            get
            {
                return SteamVR_Actions.priTaskController_TrackPadNorthClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackPadWestClick
        {
            get
            {
                return SteamVR_Actions.priTaskController_TrackPadWestClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackPadSouthClick
        {
            get
            {
                return SteamVR_Actions.priTaskController_TrackPadSouthClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackPadEastClick
        {
            get
            {
                return SteamVR_Actions.priTaskController_TrackPadEastClick;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.priTaskController_Haptic;
            }
        }
    }
}
